### ISSUE TITLE
[Feature request] Support empty payloads

### ISSUE THREAD

**Issue by LeoDog896** [1c3t3a/rust-socketio#266]
In terms of signaling for small changes (such as "broadcaster" to emit the presence of a broadcaster), empty payloads are needed.

Possibly something like so: `socket.emit("test", ())`

**Comment by 1c3t3a** [comment]
The problem is that it is not clear whether you want to send empty Json (e.g. "{}") or empty Binary payloads, so a general implementation of `From<()> for Payload` is ambiguous. What you can already do though is to provide empty byte arrays or empty json payloads, e.g. `socket.emit("test", serde_json::json!())`.
