### ISSUE TITLE
Dynamic Message Handler

### ISSUE THREAD

**Issue by ChristophKuper** [1c3t3a/rust-socketio#306]
Is there any possibility to achieve some similar behavior with the rust client ?
If not, is there a reason why this is not possible / desired ?

```
import { io } from "socket.io-client";

const socket = io("http://localhost:4200");

socket.on("connect", () => {
  socket.on("foo", (res) => {
		socket.on("bar", (res) => {
			// do somethings with bar events after a foo reached
		});
	});
});
```

**Comment by 1c3t3a** [comment]
What exactly do you mean? This is showing a different programming language, so the syntax is inherently different :)

**Comment by ChristophKuper** [comment]
Thanks for the quick reply.
The Code should just illustrate what I am trying to do.

What I am trying to do is, only after I got an event "foo" i want to start listening to another topic "bar". So all bar events are ignored until a foo event reached.

**Comment by 1c3t3a** [comment]
Mh, apparently something like this is hard to do, because registering callbacks is only possible through the `ClientBuilder`. In a callback you only have access to a `RawClient` ([source](https://docs.rs/rust_socketio/latest/rust_socketio/struct.ClientBuilder.html#method.on)) that doesn't allow to register callbacks.

**Comment by ChristophKuper** [comment]
okay, thanks for verifying
