### ISSUE TITLE
How to join/leave a socket.io room

### ISSUE THREAD

**Issue by CHCP** [1c3t3a/rust-socketio#40]
Hi there,
  I am studying the rust-socketio crate.  In my case, I need to join a socket.io room and leave this room when something happened,
so I want to known, how to join and leave a special socket.io room, I didn't found the rust functions. 

  Thanks for a lot.

**Comment by 1c3t3a** [comment]
Hi, thanks for using the crate! You're right, there are no functions concerning rooms, but that's because this crate _currently_ only implements the client and rooms is a fully server side feature. That means managing rooms in any way is done on the server side, a client does not have any information about which room he's in or even which rooms exist on the server side. For further reading visit [the official socket.io documentation](https://socket.io/docs/v4/rooms/). An example using this client would look something like this:

### server code
```javascript
// assume you've set up the server somehow
io.sockets.on('connection', function(socket) {
    // you can join (leave) a room by calling the join (leave) method
    socket.on('room', function(room) {
        socket.join(room);
    });
});

// this emits to all clients in the room
io.sockets.in("room1").emit('message', 'what is going on, party people?');
```

### client code
```rust
use serde_json::json;
// ...
// assume you've connected the client and defined callbacks for certain events
let payload = json!("room1");
socket.emit("room", payload).expect("Server unreachable");
```

**Comment by CHCP** [comment]
I see, rust-socketio is only a client crate.

Thanks a lot. @1c3t3a

**Comment by CHCP** [comment]
Do you have any plan to implement socketio server side features?

**Comment by 1c3t3a** [comment]
Actually yes, there is a tracking issue for this (#32). I will tackle it as soon as possible, but if you're interested, feel free to implement it ;)
